# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CacheItemRequest(Model):
    """CacheItemRequest.

    :param cache_key:
    :type cache_key: str
    :param table:
    :type table: str
    :param store_key:
    :type store_key: list of :class:`ValueTupleStringString <swagger.models.ValueTupleStringString>`
    :param index_name:
    :type index_name: str
    :param hash_key:
    :type hash_key: str
    """

    _attribute_map = {
        'cache_key': {'key': 'cacheKey', 'type': 'str'},
        'table': {'key': 'table', 'type': 'str'},
        'store_key': {'key': 'storeKey', 'type': '[ValueTupleStringString]'},
        'index_name': {'key': 'indexName', 'type': 'str'},
        'hash_key': {'key': 'hashKey', 'type': 'str'},
    }

    def __init__(self, cache_key=None, table=None, store_key=None, index_name=None, hash_key=None):
        self.cache_key = cache_key
        self.table = table
        self.store_key = store_key
        self.index_name = index_name
        self.hash_key = hash_key
