# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class CommitItemRequest(Model):
    """CommitItemRequest.

    :param table:
    :type table: str
    :param store_key:
    :type store_key: list of :class:`ValueTupleStringString <swagger.models.ValueTupleStringString>`
    :param item_json:
    :type item_json: str
    """

    _attribute_map = {
        'table': {'key': 'table', 'type': 'str'},
        'store_key': {'key': 'storeKey', 'type': '[ValueTupleStringString]'},
        'item_json': {'key': 'itemJson', 'type': 'str'},
    }

    def __init__(self, table=None, store_key=None, item_json=None):
        self.table = table
        self.store_key = store_key
        self.item_json = item_json
