# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class ExpiringStampRequest(Model):
    """ExpiringStampRequest.

    :param table:
    :type table: str
    :param index:
    :type index: str
    :param store_key:
    :type store_key: list of :class:`ValueTupleStringString <swagger.models.ValueTupleStringString>`
    :param stamp_key:
    :type stamp_key: :class:`ValueTupleStringString <swagger.models.ValueTupleStringString>`
    """

    _attribute_map = {
        'table': {'key': 'table', 'type': 'str'},
        'index': {'key': 'index', 'type': 'str'},
        'store_key': {'key': 'storeKey', 'type': '[ValueTupleStringString]'},
        'stamp_key': {'key': 'stampKey', 'type': 'ValueTupleStringString'},
    }

    def __init__(self, table=None, index=None, store_key=None, stamp_key=None):
        self.table = table
        self.index = index
        self.store_key = store_key
        self.stamp_key = stamp_key
