# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from .magenta_client import MagentaClient
from .version import VERSION

__all__ = ['MagentaClient']

__version__ = VERSION

