# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest import Configuration, Serializer, Deserializer
from msrest.exceptions import HttpOperationError
from msrest.pipeline import ClientRawResponse
from msrest.service_client import ServiceClient

from . import models
from .version import VERSION


class MagentaClientConfiguration(Configuration):
    """Configuration for MagentaClient
    Note that all parameters used to create this instance are saved as instance
    attributes.

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        if not base_url:
            base_url = 'http://localhost/'

        super(MagentaClientConfiguration, self).__init__(base_url)

        self.add_user_agent('magentaclient/{}'.format(VERSION))


class MagentaClient(object):
    """MagentaClient

    :ivar config: Configuration for client.
    :vartype config: MagentaClientConfiguration

    :param str base_url: Service URL
    """

    def __init__(
            self, base_url=None):

        self.config = MagentaClientConfiguration(base_url)
        self._client = ServiceClient(None, self.config)

        client_models = {k: v for k, v in models.__dict__.items() if isinstance(v, type)}
        self.api_version = 'v1'
        self._serialize = Serializer(client_models)
        self._deserialize = Deserializer(client_models)


    def gl_login_get(
            self, custom_headers=None, raw=False, **operation_config):
        """

        :param dict custom_headers: headers that will be added to the request
        :param bool raw: returns the direct response alongside the deserialized response
        :param operation_config: :ref:`Operation configuration overrides<msrest:optionsforoperations>`.
        :return: None or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>` if raw=true
        :rtype: None or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`
        :raises: :class:`HttpOperationError<msrest.exceptions.HttpOperationError>`
        """
        # Construct URL
        url = '/gl/login'

        # Construct parameters
        query_parameters = {}

        # Construct headers
        header_parameters = {}
        header_parameters['Content-Type'] = 'application/json; charset=utf-8'
        if custom_headers:
            header_parameters.update(custom_headers)

        # Construct and send request
        request = self._client.get(url, query_parameters)
        response = self._client.send(request, header_parameters, **operation_config)

        if response.status_code not in [200]:
            raise HttpOperationError(self._deserialize, response)

        if raw:
            client_raw_response = ClientRawResponse(None, response)
            return client_raw_response

    def gl_logout_get(
            self, custom_headers=None, raw=False, **operation_config):
        """

        :param dict custom_headers: headers that will be added to the request
        :param bool raw: returns the direct response alongside the deserialized response
        :param operation_config: :ref:`Operation configuration overrides<msrest:optionsforoperations>`.
        :return: None or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>` if raw=true
        :rtype: None or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`
        :raises: :class:`HttpOperationError<msrest.exceptions.HttpOperationError>`
        """
        # Construct URL
        url = '/gl/logout'

        # Construct parameters
        query_parameters = {}

        # Construct headers
        header_parameters = {}
        header_parameters['Content-Type'] = 'application/json; charset=utf-8'
        if custom_headers:
            header_parameters.update(custom_headers)

        # Construct and send request
        request = self._client.get(url, query_parameters)
        response = self._client.send(request, header_parameters, **operation_config)

        if response.status_code not in [200]:
            raise HttpOperationError(self._deserialize, response)

        if raw:
            client_raw_response = ClientRawResponse(None, response)
            return client_raw_response

    def api_v1_user_get(
            self, custom_headers=None, raw=False, **operation_config):
        """

        :param dict custom_headers: headers that will be added to the request
        :param bool raw: returns the direct response alongside the deserialized response
        :param operation_config: :ref:`Operation configuration overrides<msrest:optionsforoperations>`.
        :return: None or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>` if raw=true
        :rtype: None or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`
        :raises: :class:`HttpOperationError<msrest.exceptions.HttpOperationError>`
        """
        # Construct URL
        url = '/api/v1/user'

        # Construct parameters
        query_parameters = {}

        # Construct headers
        header_parameters = {}
        header_parameters['Content-Type'] = 'application/json; charset=utf-8'
        if custom_headers:
            header_parameters.update(custom_headers)

        # Construct and send request
        request = self._client.get(url, query_parameters)
        response = self._client.send(request, header_parameters, **operation_config)

        if response.status_code not in [200]:
            raise HttpOperationError(self._deserialize, response)

        if raw:
            client_raw_response = ClientRawResponse(None, response)
            return client_raw_response

    def api_v1_user_agree_post(
            self, value=None, custom_headers=None, raw=False, **operation_config):
        """

        :param value:
        :type value: object
        :param dict custom_headers: headers that will be added to the request
        :param bool raw: returns the direct response alongside the deserialized response
        :param operation_config: :ref:`Operation configuration overrides<msrest:optionsforoperations>`.
        :return: bool or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>` if raw=true
        :rtype: bool or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`
        :raises: :class:`HttpOperationError<msrest.exceptions.HttpOperationError>`
        """
        # Construct URL
        url = '/api/v1/user/agree'

        # Construct parameters
        query_parameters = {}

        # Construct headers
        header_parameters = {}
        header_parameters['Content-Type'] = 'application/json-patch+json; charset=utf-8'
        if custom_headers:
            header_parameters.update(custom_headers)

        # Construct body
        if value is not None:
            body_content = self._serialize.body(value, 'object')
        else:
            body_content = None

        # Construct and send request
        request = self._client.post(url, query_parameters)
        response = self._client.send(
            request, header_parameters, body_content, **operation_config)

        if response.status_code not in [200]:
            raise HttpOperationError(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('bool', response)

        if raw:
            client_raw_response = ClientRawResponse(deserialized, response)
            return client_raw_response

        return deserialized

    def get_root_account(
            self, custom_headers=None, raw=False, **operation_config):
        """

        :param dict custom_headers: headers that will be added to the request
        :param bool raw: returns the direct response alongside the deserialized response
        :param operation_config: :ref:`Operation configuration overrides<msrest:optionsforoperations>`.
        :return: :class:`RootAccount <swagger.models.RootAccount>` or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>` if raw=true
        :rtype: :class:`RootAccount <swagger.models.RootAccount>` or :class:`ClientRawResponse<msrest.pipeline.ClientRawResponse>`
        :raises: :class:`HttpOperationError<msrest.exceptions.HttpOperationError>`
        """
        # Construct URL
        url = '/api/v1/user/RootAccount'

        # Construct parameters
        query_parameters = {}

        # Construct headers
        header_parameters = {}
        header_parameters['Content-Type'] = 'application/json; charset=utf-8'
        if custom_headers:
            header_parameters.update(custom_headers)

        # Construct and send request
        request = self._client.get(url, query_parameters)
        response = self._client.send(request, header_parameters, **operation_config)

        if response.status_code not in [200]:
            raise HttpOperationError(self._deserialize, response)

        deserialized = None

        if response.status_code == 200:
            deserialized = self._deserialize('RootAccount', response)

        if raw:
            client_raw_response = ClientRawResponse(deserialized, response)
            return client_raw_response

        return deserialized
