// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DynorisClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CacheItemRequest
    {
        /// <summary>
        /// Initializes a new instance of the CacheItemRequest class.
        /// </summary>
        public CacheItemRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CacheItemRequest class.
        /// </summary>
        public CacheItemRequest(string cacheKey = default(string), string table = default(string), IList<ValueTupleStringString> storeKey = default(IList<ValueTupleStringString>), string indexName = default(string), string hashKey = default(string))
        {
            CacheKey = cacheKey;
            Table = table;
            StoreKey = storeKey;
            IndexName = indexName;
            HashKey = hashKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cacheKey")]
        public string CacheKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeKey")]
        public IList<ValueTupleStringString> StoreKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexName")]
        public string IndexName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hashKey")]
        public string HashKey { get; set; }

    }
}
