// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Dynoris.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CacheItemRequest
    {
        /// <summary>
        /// Initializes a new instance of the CacheItemRequest class.
        /// </summary>
        public CacheItemRequest() { }

        /// <summary>
        /// Initializes a new instance of the CacheItemRequest class.
        /// </summary>
        public CacheItemRequest(string cacheKey = default(string), string table = default(string), IList<ValueTupleStringString> storeKey = default(IList<ValueTupleStringString>), string indexName = default(string), string hashKey = default(string))
        {
            CacheKey = cacheKey;
            Table = table;
            StoreKey = storeKey;
            IndexName = indexName;
            HashKey = hashKey;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cacheKey")]
        public string CacheKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeKey")]
        public IList<ValueTupleStringString> StoreKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexName")]
        public string IndexName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hashKey")]
        public string HashKey { get; set; }

    }
}
