// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DynorisClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CommitItemRequest
    {
        /// <summary>
        /// Initializes a new instance of the CommitItemRequest class.
        /// </summary>
        public CommitItemRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommitItemRequest class.
        /// </summary>
        public CommitItemRequest(string table = default(string), IList<ValueTupleStringString> storeKey = default(IList<ValueTupleStringString>), string itemJson = default(string))
        {
            Table = table;
            StoreKey = storeKey;
            ItemJson = itemJson;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeKey")]
        public IList<ValueTupleStringString> StoreKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemJson")]
        public string ItemJson { get; set; }

    }
}
