// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Dynoris.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class CommitItemRequest
    {
        /// <summary>
        /// Initializes a new instance of the CommitItemRequest class.
        /// </summary>
        public CommitItemRequest() { }

        /// <summary>
        /// Initializes a new instance of the CommitItemRequest class.
        /// </summary>
        public CommitItemRequest(string table = default(string), IList<ValueTupleStringString> storeKey = default(IList<ValueTupleStringString>), string itemJson = default(string))
        {
            Table = table;
            StoreKey = storeKey;
            ItemJson = itemJson;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeKey")]
        public IList<ValueTupleStringString> StoreKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "itemJson")]
        public string ItemJson { get; set; }

    }
}
