// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace DynorisClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ExpiringStampRequest
    {
        /// <summary>
        /// Initializes a new instance of the ExpiringStampRequest class.
        /// </summary>
        public ExpiringStampRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ExpiringStampRequest class.
        /// </summary>
        public ExpiringStampRequest(string table = default(string), string index = default(string), IList<ValueTupleStringString> storeKey = default(IList<ValueTupleStringString>), ValueTupleStringString stampKey = default(ValueTupleStringString))
        {
            Table = table;
            Index = index;
            StoreKey = storeKey;
            StampKey = stampKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "index")]
        public string Index { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeKey")]
        public IList<ValueTupleStringString> StoreKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stampKey")]
        public ValueTupleStringString StampKey { get; set; }

    }
}
