// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Dynoris.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ExpiringStampRequest
    {
        /// <summary>
        /// Initializes a new instance of the ExpiringStampRequest class.
        /// </summary>
        public ExpiringStampRequest() { }

        /// <summary>
        /// Initializes a new instance of the ExpiringStampRequest class.
        /// </summary>
        public ExpiringStampRequest(string table = default(string), string index = default(string), IList<ValueTupleStringString> storeKey = default(IList<ValueTupleStringString>), ValueTupleStringString stampKey = default(ValueTupleStringString))
        {
            Table = table;
            Index = index;
            StoreKey = storeKey;
            StampKey = stampKey;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "table")]
        public string Table { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "index")]
        public string Index { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "storeKey")]
        public IList<ValueTupleStringString> StoreKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stampKey")]
        public ValueTupleStringString StampKey { get; set; }

    }
}
