# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from .dynoris_client import DynorisClient
from .version import VERSION

__all__ = ['DynorisClient']

__version__ = VERSION

