# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Link(Model):
    """Link.

    :param source:
    :type source: :class:`SocialAccount <swagger.models.SocialAccount>`
    :param target:
    :type target: :class:`SocialAccount <swagger.models.SocialAccount>`
    :param filters:
    :type filters: object
    :param options:
    :type options: object
    :param schedule:
    :type schedule: :class:`Schedule <swagger.models.Schedule>`
    :param bound_stamp:
    :type bound_stamp: long
    :param updated_stamp:
    :type updated_stamp: long
    """

    _attribute_map = {
        'source': {'key': 'source', 'type': 'SocialAccount'},
        'target': {'key': 'target', 'type': 'SocialAccount'},
        'filters': {'key': 'filters', 'type': 'object'},
        'options': {'key': 'options', 'type': 'object'},
        'schedule': {'key': 'schedule', 'type': 'Schedule'},
        'bound_stamp': {'key': 'boundStamp', 'type': 'long'},
        'updated_stamp': {'key': 'updatedStamp', 'type': 'long'},
    }

    def __init__(self, source=None, target=None, filters=None, options=None, schedule=None, bound_stamp=None, updated_stamp=None):
        self.source = source
        self.target = target
        self.filters = filters
        self.options = options
        self.schedule = schedule
        self.bound_stamp = bound_stamp
        self.updated_stamp = updated_stamp
