# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class RootAccount(Model):
    """RootAccount.

    :param account:
    :type account: :class:`SocialAccount <swagger.models.SocialAccount>`
    :param accounts:
    :type accounts: dict
    :param links:
    :type links: dict
    :param logs:
    :type logs: dict
    """

    _attribute_map = {
        'account': {'key': 'account', 'type': 'SocialAccount'},
        'accounts': {'key': 'accounts', 'type': '{SocialAccount}'},
        'links': {'key': 'links', 'type': '{Link}'},
        'logs': {'key': 'logs', 'type': '{LogItem}'},
    }

    def __init__(self, account=None, accounts=None, links=None, logs=None):
        self.account = account
        self.accounts = accounts
        self.links = links
        self.logs = logs
