# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class Schedule(Model):
    """Schedule.

    :param enabled:
    :type enabled: bool
    :param days:
    :type days: object
    """

    _attribute_map = {
        'enabled': {'key': 'enabled', 'type': 'bool'},
        'days': {'key': 'days', 'type': 'object'},
    }

    def __init__(self, enabled=None, days=None):
        self.enabled = enabled
        self.days = days
