# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class SocialAccount(Model):
    """SocialAccount.

    :param provider:
    :type provider: str
    :param pid:
    :type pid: str
    :param info:
    :type info: object
    :param credentials:
    :type credentials: object
    :param errors:
    :type errors: int
    :param posted_set:
    :type posted_set: object
    :param message_map:
    :type message_map: object
    :param last_publish:
    :type last_publish: long
    """

    _attribute_map = {
        'provider': {'key': 'provider', 'type': 'str'},
        'pid': {'key': 'pid', 'type': 'str'},
        'info': {'key': 'info', 'type': 'object'},
        'credentials': {'key': 'credentials', 'type': 'object'},
        'errors': {'key': 'errors', 'type': 'int'},
        'posted_set': {'key': 'postedSet', 'type': 'object'},
        'message_map': {'key': 'messageMap', 'type': 'object'},
        'last_publish': {'key': 'lastPublish', 'type': 'long'},
    }

    def __init__(self, provider=None, pid=None, info=None, credentials=None, errors=None, posted_set=None, message_map=None, last_publish=None):
        self.provider = provider
        self.pid = pid
        self.info = info
        self.credentials = credentials
        self.errors = errors
        self.posted_set = posted_set
        self.message_map = message_map
        self.last_publish = last_publish
